<?php 
/**
 * @category   FZ
 * @package    FZ_GoogleAnalytics
 * @author     Francesco Zoccarato <francesco.zoccarato@gmail.com>
 */
?>
<div id="ga-realtime-console">
    <button id="ga-realtime-toggle-play-pause" class="ga-realtime-action" onclick="FZ.GoogleAnalitycs.Realtime.toggle();return false;"><span><span><?php echo $this->__('Play'); ?></span></span></button>
    <button id="ga-realtime-reload" class="ga-realtime-action" onclick="FZ.GoogleAnalitycs.Realtime.play(false);return false;"><span><span><?php echo $this->__('Reload now'); ?></span></span></button>
</div>